site_name: Datascene – Référentiel des métadonnées descriptives du spectacle
theme:
  name: material
  language: fr
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
  custom_dir: overrides
  logo: assets/Datascene_White.svg
  favicon: assets/Datascene_White_carre.svg
markdown_extensions:
  - toc:
      permalink: true
      title: Sur cette page
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
copyright: Copyright &copy; 2024 Datascence – Référentiel des métadonnées descriptives du spectacle – <a href="#__consent">Gérer les cookies</a>
plugins:
    - search
    - macros
nav:
  - À propos:
    - Bienvenue: 'index.md'
    - Contact: 'contact.md'
    - Contribuer: 'contribuer.md'
    - Crédits: 'credits.md'
    - Droits d'utilisation: 'droits.md'
  - Avant de commencer:
    - Objectifs: 'avant_de_commencer/objectifs.md'
    - Composantes: 'avant_de_commencer/composantes.md'
    - Lignes directrices: 'avant_de_commencer/lignes_directrices.md'
    - Glossaire: 'references/glossaire.md'
  - Modèle de données:
    - 'modele/index.md'
    - Classes principales:
      - modele/classes_principales/index.md
      - Spectacle (show): 'references/proprietes/show.md'
      - Représentation (performance): 'references/proprietes/performance.md'
      - Série (series): 'references/proprietes/series.md'
      - Lieu (place): 'references/proprietes/place.md'
      - Salle (room): 'references/proprietes/room.md'
      - Contributeur (contributor): 'references/proprietes/contributor.md'
      - Oeuvre (work): 'references/proprietes/work.md'
    - Classes utilitaires:
      - modele/classes_utilitaires/index.md
      - Identifiant (identifier): 'references/proprietes/utilities/identifier.md'
      - Offre (offer): 'references/proprietes/utilities/offer.md'
      - Contribution (contribution): 'references/proprietes/utilities/contribution.md'
      - Terme (term): 'references/proprietes/utilities/term.md'
      - Média (term): 'references/proprietes/utilities/media.md'
      - Adresse (postal_address): 'references/proprietes/utilities/postal_address.md'
    - Propriétés des classes: 'modele/proprietes_des_classes.md'
    - Vocabulaires contrôlés:
      - modele/vocabulaires_controles/index.md
      - Accessibilité universelle: 'references/vocabulaires/accessibiliteUniversellesTermes'
      - Avertissements: 'references/vocabulaires/avertissement.md'
      - Disciplines artistiques: 'references/vocabulaires/disciplines-asq.md'
      - Public cible: 'references/vocabulaires/publicCible.md'
      - Types d'associations géographiques: 'references/vocabulaires/associationGeographiqueType.md'
      - Types de configurations de salles: 'references/vocabulaires/configurationSalleTermes.md'
      - Types de contenus: 'references/vocabulaires/contenusType.md'
      - Types de contributions: 'references/vocabulaires/contributionType.md'
    - Types de propriétés: 'references/types.md'
    - Exemples: 'references/exemples.md'
extra:
  analytics:
    provider: google
    property: G-PTQ0P6RZLD
  consent:
    title: Nous respectons votre vie privée
    description: >-
      En cliquant sur « Autoriser tous les cookies », vous acceptez le stockage de cookies sur votre
      appareil pour améliorer la navigation sur le site, analyser son utilisation et contribuer à nos
      efforts de diffusion de Datascene.
hooks:
  - schema_to_markdown.py
  - vocabularies_to_markdown.py