site_name: Datascene – Référentiel des métadonnées descriptives du spectacle
theme:
  name: material
  language: fr
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - content.code.copy
  custom_dir: overrides
  logo: assets/Datascene_White.svg
  favicon: assets/Datascene_White_carre.svg
markdown_extensions:
  - toc:
      permalink: true
      title: Sur cette page
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
copyright: Copyright &copy; 2026 Datascène – Référentiel des métadonnées descriptives du spectacle – <a href="#__consent">Gérer les cookies</a>
plugins:
    - search
    - macros
nav:
  - À propos:
    - Bienvenue: 'index.md'
    - Droits d'utilisation: 'droits.md'
  - Modèle de données:
    - 'modele/index.md'
    - Classes principales:
      - modele/classes_principales/index.md
      - Spectacle (show): 'references/show.md'
      - Représentation (performance): 'references/performance.md'
      - Série (series): 'references/series.md'
      - Lieu (place): 'references/place.md'
      - Salle (room): 'references/room.md'
      - Contributeur (contributor): 'references/contributor.md'
      - Oeuvre (work): 'references/work.md'
    - Classes utilitaires:
      - modele/classes_utilitaires/index.md
      - Identifiant (identifier): 'references/identifier.md'
      - Offre (offer): 'references/offer.md'
      - Contribution (contribution): 'references/contribution.md'
      - Terme (term): 'references/term.md'
      - Média (term): 'references/media.md'
      - Adresse (postal_address): 'references/postal_address.md'
  - Vocabulaires contrôlés:
    - modele/vocabulaires_controles/index.md
    - Accessibilité universelle: 'references/vocabularies/accessibiliteUniversellesTermes.md'
    - Avertissements: 'references/vocabularies/avertissement.md'
    - Disciplines artistiques: 'references/vocabularies/disciplines-asq.md'
    - Public cible: 'references/vocabularies/publicCible.md'
    - Types d'associations géographiques: 'references/vocabularies/associationGeographiqueType.md'
    - Types de configurations de salles: 'references/vocabularies/configurationSalleTermes.md'
    - Types de contenus: 'references/vocabularies/contenusType.md'
    - Types de contributions: 'references/vocabularies/contributionType.md'
  - Exemple: 'references/exemples.md'
extra:
  analytics:
    provider: google
    property: G-PTQ0P6RZLD
  consent:
    title: Nous respectons votre vie privée
    description: >-
      En cliquant sur « Autoriser tous les cookies », vous acceptez le stockage de cookies sur votre
      appareil pour améliorer la navigation sur le site, analyser son utilisation et contribuer à nos
      efforts de diffusion de Datascene.
hooks:
  - schema_to_markdown.py
  - vocabularies_to_markdown.py